version: "3"

services:
  front:
    image: meliszhold/sun_front
    container_name: front
    depends_on:
      - api

  api:
    image: meliszhold/sun_api
    container_name: api

  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front
